  # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
  # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

  name: Node.js CI
  
  env:
    AZURE_WEBAPP_NAME: devops-harkka-app

  on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
      
  permissions:
    contents: 'read'
    packages: 'write'


  jobs:
    build:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- --watch=false --browsers=ChromeHeadless

      - uses: actions/upload-artifact@v3 
        with:
           name: my-artifact
           path: dist/angular-example-app
           
    build-docker: 
      runs-on: ubuntu-latest
      needs: build

      steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        with:
         name: my-artifact
         path: dist/angular-example-app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest

      needs: build

      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Lowercase the repo name
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
